#!/usr/bin/perl -w

=Synopsis
DESCRIPTION		: Generate multiple input files for grompp and mdrun.
				  The primary use was to run multiple simulations with different seed values.
				  Input files generated by the energy minimization will be picked 
				  from the current directory.
DEPENDENCIES	: Gromacs
INPUT			: number of simulations to run
OUTPUT			: nvt run, npt run and md tpr files
AUTHOR			: Dr. Rohit Farmer
LAST MODIFIED	: 24/05/2016
=cut

use strict;
use warnings;

################ USAGE CHECK ##################
if (   $#ARGV < 0
	or $ARGV[0] eq 'help'
	or $ARGV[0] eq 'h' )
{
	print "Usage: master_md.pl number\n";
	exit -1;
}
###############################################

my $NoOfRuns=$ARGV[0];

for(my $i=0; $i<$NoOfRuns; $i++)
 {
  system "grompp -f nvt.mdp -c em.gro -p topol.top -o nvt_$i.tpr";
  system "mdrun -v -s nvt_$i.tpr -deffnm nvt_$i";
 }
 
 for(my $j=0; $j<$NoOfRuns; $j++)
 {
   system "grompp -f npt.mdp -c nvt_$j.gro -t nvt_$j.cpt -p topol.top -o npt_$j.tpr";
   system "mdrun -v -s npt_$j.tpr -deffnm npt_$j";
 }

for(my $k=0; $k<$NoOfRuns; $k++)
 {
   system "grompp -f md.mdp -c npt_$k.gro -t npt_$k.cpt -p topol.top -o md_$k.tpr";
 }
